**Suma de matrices:**

Para sumar dos matrices, simplemente utilizamos el operador *+*, aunque deben tener la misma dimensión.

In [1]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma = matriz1 + matriz2
print("Suma de matrices:")
print(suma)

Suma de matrices:
[[ 6  8]
 [10 12]]


**Multiplicación entre matrices:**

 Utilizamos el método dot() o el operador @ para multiplicar matrices

In [3]:
multiplicacion = matriz1.dot(matriz2)
multiplicacion2 = matriz1 @ matriz2

print("Multiplicación entre matrices:")


print(multiplicacion)
print(multiplicacion2)

Multiplicación entre matrices:
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**Multiplicación por escalar:**

Multiplicamos cada elemento de la matriz por un número escalar

In [4]:
escalar = 2
matriz_escalar = matriz1 * escalar
print("Matriz multiplicada por escalar:")
print(matriz_escalar)


Matriz multiplicada por escalar:
[[2 4]
 [6 8]]


**Cálculo de inversa:**

Para calcular la inversa de una matriz, utilizamos np.linalg.inv()

In [5]:
matriz_inversa = np.linalg.inv(matriz1)
print("Matriz inversa:")
print(matriz_inversa)


Matriz inversa:
[[-2.   1. ]
 [ 1.5 -0.5]]


**Cálculo del determinante:**

El determinante de una matriz se obtiene con np.linalg.det().

In [6]:
determinante = np.linalg.det(matriz1)
print("Determinante:")
print(determinante)


Determinante:
-2.0000000000000004


**Solución por Gauss-Jordan:**

Para resolver sistemas de ecuaciones lineales, podemos usar np.linalg.solve().

In [7]:
b = np.array([5, 6])
solucion = np.linalg.solve(matriz1, b)
print("Solución por Gauss-Jordan:")
print(solucion)


Solución por Gauss-Jordan:
[-4.   4.5]


**Construir una matriz identidad:**

La matriz identidad se crea con np.eye(n), donde n es el tamaño deseado.

In [8]:
matriz_identidad = np.eye(3)  # Matriz 3x3
print("Matriz identidad:")
print(matriz_identidad)


Matriz identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Matriz nula:**

Creamos una matriz de ceros con np.zeros((filas, columnas))

In [9]:
matriz_nula = np.zeros((2, 3))  # Matriz 2x3
print("Matriz nula:")
print(matriz_nula)


Matriz nula:
[[0. 0. 0.]
 [0. 0. 0.]]


**Matriz diagonal n × n:**

Creamos una matriz diagonal con np.diag([valores])

In [10]:
valores_diagonal = [1, 2, 3]
matriz_diagonal = np.diag(valores_diagonal)
print("Matriz diagonal:")
print(matriz_diagonal)


Matriz diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [19]:
economiaIsrael = np.array([[0.293, 0 , 0], [0.014, 0.207, 0.017],[0.044, 0.010, 0.216]])
matriz_identidad1 = np.eye(3)
print("Matriz tecnologica")
print(economiaIsrael)

resta= matriz_identidad1 - economiaIsrael

print(resta)


c = np.array([0.13213, 0.17597, 0.1786])
exportacion = np.linalg.inv(resta)
ecuacioneLineales= np.dot(exportacion,c)

print("Porcentaje en libras de exportación necesaria, o bien, matriz de Leontief:")
print(ecuacioneLineales)


exportacion2 = np.linalg.solve(resta, c)
print("Resultado por Gauss Jordan")
print(exportacion2)



Matriz tecnologica
[[0.293 0.    0.   ]
 [0.014 0.207 0.017]
 [0.044 0.01  0.216]]
[[ 0.707  0.     0.   ]
 [-0.014  0.793 -0.017]
 [-0.044 -0.01   0.784]]
Porcentaje en libras de exportación necesaria, o bien, matriz de Leontief:
[0.18688826 0.23037503 0.24123321]
Resultado por Gauss Jordan
[0.18688826 0.23037503 0.24123321]


En este código, se calcula primero la inversa de la matriz de coeficientes (resta, que es valor después de las operaciones previas) utilizando np.linalg.inv(). Luego, se resuelve el sistema de ecuaciones lineales multiplicando la matriz inversa por el vector de términos independientes utilizando la función np.dot(). Finalmente, se imprime el resultado. Este método es equivalente al método de eliminación de Gauss, pero utiliza la inversa de la matriz en lugar de realizar operaciones de eliminación.

**Generalizar el codigo para dar solución a un modelo de economía con n sectores y mostrar un ejemplo con n=10**

In [22]:
import numpy as np

def solve_leontief_model(n):
    # Genera una matriz tecnológica aleatoria (n x n)
    economia = np.random.rand(n, n)
    print(economia)

    # Crea la matriz identidad (n x n)
    matriz_identidad = np.eye(n)

    # Calcula la diferencia entre la matriz identidad y la matriz tecnológica
    resta = matriz_identidad - economia

    # Genera un vector de consumo aleatorio (n elementos)
    c = np.random.rand(n)

    # Calcula la inversa de la matriz de diferencia
    exportacion = np.linalg.inv(resta)

    # Resuelve las ecuaciones lineales
    ecuacioneLineales = np.dot(exportacion, c)

    return ecuacioneLineales

# Ejemplo con n = 10
n_sectores = 10
result = solve_leontief_model(n_sectores)
print(f"Porcentaje en millones de pesos/libras o dolares de exportación necesaria (matriz de Leontief) para {n_sectores} sectores:")
print(result)


[[0.90243585 0.55055786 0.3063648  0.22263337 0.63354517 0.41671993
  0.78775654 0.58073874 0.51624989 0.90946241]
 [0.68758106 0.70723514 0.54579004 0.14515123 0.79143486 0.71966244
  0.60020241 0.18488044 0.23775411 0.95864485]
 [0.33981859 0.23049085 0.32103126 0.15935555 0.20169149 0.58354496
  0.04769124 0.86748288 0.45255649 0.50616287]
 [0.83451015 0.46150267 0.83687955 0.69777145 0.32703323 0.80762467
  0.46373212 0.70635379 0.09622278 0.63209589]
 [0.2149893  0.35624126 0.10090136 0.59168418 0.03797419 0.35417915
  0.61801031 0.80213842 0.11268314 0.58541834]
 [0.32766944 0.20515788 0.83137147 0.03841425 0.39817403 0.36517853
  0.20378409 0.06560943 0.49805186 0.55372161]
 [0.80192372 0.55395857 0.2301404  0.35696846 0.06444806 0.19718311
  0.04830836 0.92046772 0.23503562 0.76379145]
 [0.52780822 0.58395248 0.48113006 0.91892551 0.90693476 0.63665559
  0.40111947 0.5985315  0.74455368 0.47838568]
 [0.38687493 0.97819561 0.88306527 0.95932222 0.31716199 0.21886163
  0.6113497 